#ifndef GSTRTPPLAYER_GLOBAL_H
#define GSTRTPPLAYER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GSTRTPVIDEO_LIBRARY)
#  define GSTRTPVIDEOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GSTRTPVIDEOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GSTRTPPLAYER_GLOBAL_H
